src/Senparc.Areas.Admin/Areas/Admin/Pages/AdminUserInfo/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Senparc.CO2NET.Extensions;
using Senparc.CO2NET.Trace;
using Senparc.Core.Models;
using Senparc.Scf.Core.Enums;
using Senparc.Scf.Core.Models;
using Senparc.Scf.Core.Validator;
using Senparc.Scf.Service;
using Senparc.Service;

namespace Senparc.Areas.Admin.Areas.Admin.Pages
{
    public class AdminUserInfo_EditModel : BaseAdminPageModel, IValidatorEnvironment
    {
        /// <summary>
        /// Id
        /// </summary>
        [BindProperty]
        public int Id { get; set; }

        public bool IsEdit { get; set; }


        [BindProperty]
        public CreateOrUpdate_AdminUserInfoDto AdminUserInfo { get; set; } = new CreateOrUpdate_AdminUserInfoDto();
        //public CreateUpdate_AdminUserInfoDto AdminUserInfo { get; set; }

        private readonly IServiceProvider _serviceProvider;
        private readonly AdminUserInfoService _adminUserInfoService;

        public AdminUserInfo_EditModel(IServiceProvider serviceProvider,AdminUserInfoService adminUserInfoService)
        {
            _serviceProvider = serviceProvider;
            _adminUserInfoService = adminUserInfoService;
        }

        public IActionResult OnGet(int id)
        {
            IsEdit = id > 0;
            if (IsEdit)
            {
                AdminUserInfo = _adminUserInfoService.GetAdminUserInfo(id);
                if (AdminUserInfo == null)
                {
                    throw new Exception("信息不存在！");//TODO:临时
                    //return RenderError("信息不存在！");
                }
             
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            IsEdit = Id > 0;
            this.Validator(AdminUserInfo.UserName, "用户名", "UserName", false)
                .IsFalse(z => this._adminUserInfoService.CheckUserNameExisted(Id, z), "用户名已存在！", true);
            if (!IsEdit)
            {

                this.Validator(AdminUserInfo.Password, "密码", "Password", false).MinLength(6);
            }
            else
            {
                if (!AdminUserInfo.Password.IsNullOrEmpty())
                {
                    this.Validator(AdminUserInfo.Password, "密码", "Password", false).MinLength(6);
                }
            }

            if (!ModelState.IsValid)
            {
                return Page();
            }

            ////执行数据库备份
            //var backupFile = @$"SCF-Backup-{SystemTime.Now.ToString("yyyy-MM-dd-HH-mm-ss")}.bak";
            //SenparcTrace.SendCustomLog("开始执行数据库备份", backupFile);
            //var dbToolkitFunction = new Senparc.Xscf.DatabaseToolkit.Functions.BackupDatabase(_serviceProvider);
            //var dbToolkitParam = new Senparc.Xscf.DatabaseToolkit.Functions.BackupDatabase.BackupDatabase_Parameters()
            //{
            //    Path = @$"E:\Senparc项目\SenparcCoreFramework\SCF\src\Senparc.Web\App_Data\DataBase\{backupFile}"
            //};
            //dbToolkitFunction.Run(dbToolkitParam);
            //SenparcTrace.SendCustomLog("数据库备份完毕", "完整路径" + dbToolkitParam.Path);

            if (IsEdit)
            {
                AdminUserInfo.Id = Id;
                _adminUserInfoService.UpdateAdminUserInfo(AdminUserInfo);
            }
            else
            {
                _adminUserInfoService.CreateAdminUserInfo(AdminUserInfo);
            }

            base.SetMessager(MessageType.success, $"{(IsEdit ? "修改" : "新增")}成功！");
            return RedirectToPage("./Index");
        }
    }
}

src/Senparc.Areas.Admin/Areas/Admin/Pages/Menu/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Senparc.Core.Models.DataBaseModel;
using Senparc.Scf.Core.Models;
using Senparc.Scf.Core.Models.DataBaseModel;
using Senparc.Scf.Service;
using Senparc.Service;

namespace Senparc.Areas.Admin.Areas.Admin.Pages
{
    public class MenuEditModel : BaseAdminPageModel
    {
        private readonly SysMenuService _sysMenuService;
        private readonly SysButtonService _sysButtonService;

        public MenuEditModel(SysMenuService _sysMenuService, SysButtonService _sysButtonService)
        {
            CurrentMenu = "Menu";
            this._sysMenuService = _sysMenuService;
            this._sysButtonService = _sysButtonService;
        }

        [BindProperty(SupportsGet = true)]
        public string Id { get; set; }

        public SysMenuDto SysMenuDto { get; set; }

        public IEnumerable<SysButton> SysButtons { get; set; }

        public async Task OnGetAsync()
        {
            if (!string.IsNullOrEmpty(Id))
            {
                var entity = await _sysMenuService.GetObjectAsync(_ => _.Id == Id);
                SysButtons = await _sysButtonService.GetFullListAsync(_ => _.MenuId == Id);

                SysMenuDto = _sysMenuService.Mapper.Map<SysMenuDto>(entity);
            }
            else
            {
                SysMenuDto = new SysMenuDto() { Visible = true };
                SysButtons = new List<SysButton>() { new SysButton() };
            }
        }

        public async Task<IActionResult> OnGetDetailAsync(string id)
        {
            var entity = await _sysMenuService.GetObjectAsync(_ => _.Id == Id);
            var sysMenuDto = _sysMenuService.Mapper.Map<SysMenuDto>(entity);
            var sysButtons = await _sysButtonService.GetFullListAsync(_ => _.MenuId == Id);
            return Ok( new{ sysMenuDto, sysButtons });
        }

        /// <summary>
        /// 获取菜单
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> OnGetMenuAsync()
        {
            return Ok(await _sysMenuService.GetMenuDtoByCacheAsync());
        }

        /// <summary>
        /// 获取菜单下的按钮
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> OnGetButtonsAsync(string menuId)
        {
            return Ok(await _sysButtonService.GetSysButtonDtosAsync(menuId));
        }

        public async Task<IActionResult> OnPostDeleteButtonAsync(string buttonId)
        {
            if (string.IsNullOrEmpty(buttonId))
            {
                return Ok(false);
            }
            await _sysButtonService.DeleteObjectAsync(_ => _.Id == buttonId);
            return Ok(true);
        }

        public async Task<IActionResult> OnPostDeleteAsync(string[] ids)
        {
            var entity = await _sysMenuService.GetFullListAsync(_ => ids.Contains(_.Id) && _.IsLocked == false);
            var buttons = await _sysButtonService.GetFullListAsync(_ => ids.Contains(_.MenuId));

            await _sysButtonService.DeleteAllAsync(buttons);
            await _sysMenuService.DeleteAllAsync(entity);
            await _sysMenuService.RemoveMenuAsync();
            IEnumerable<string> unDeleteIds = ids.Except(entity.Select(_ => _.Id));
            return Ok(unDeleteIds);
        }

        public async Task<IActionResult> OnPostAddMenuAsync(SysMenuDto sysMenu)
        {
            if (string.IsNullOrEmpty(sysMenu.MenuName))
            {
                return Ok("菜单名称不能为空", false, "菜单名称不能为空");
            }
            var entity = await _sysMenuService.CreateOrUpdateAsync(sysMenu);
            return Ok(entity.Id);
        }

        public async Task<IActionResult> OnPostAsync(SysMenuDto sysMenuDto, IEnumerable<SysButtonDto> buttons)
        {
            if (!ModelState.IsValid)
            {
                return Ok("模型验证未通过", false, "模型验证未通过");
            }

            await _sysMenuService.CreateOrUpdateAsync(sysMenuDto, buttons);

            return Ok(new { buttons, sysMenuDto });
        }
    }
}

src/Senparc.Areas.Admin/Areas/Admin/Pages/Role/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Senparc.Core.Models.DataBaseModel;
using Senparc.Scf.Core.Models.DataBaseModel;
using Senparc.Scf.Service;
using Senparc.Service;

namespace Senparc.Areas.Admin.Areas.Admin.Pages
{
    public class RoleEditModel : BaseAdminPageModel
    {
        private readonly SysRoleService _sysRoleService;

        public RoleEditModel(SysRoleService sysRoleService)
        {
            CurrentMenu = "Role";
            _sysRoleService = sysRoleService;
        }

        [BindProperty(SupportsGet = true)]
        public string Id { get; set; }

        [BindProperty]
        public SysRoleDto SysRoleDto { get; set; }

        public async Task OnGetAsync()
        {
            if (!string.IsNullOrEmpty(Id))
            {
                var entity = await _sysRoleService.GetObjectAsync(_ => _.Id == Id);
                SysRoleDto = _sysRoleService.Mapper.Map<SysRoleDto>(entity);
            }
        }

        public async Task<IActionResult> OnPostAsync()
        {
            //if (!string.IsNullOrEmpty(Id))
            //{
            //    var entity = await _sysRoleService.GetObjectAsync(_ => _.Id == Id);
            //    SysRoleDto = _sysRoleService.Mapper.Map<SysRoleDto>(entity);
            //}
            await _sysRoleService.CreateOrUpdateAsync(SysRoleDto);
            return RedirectToPage("./Index");
        }
    }
}

src/Senparc.Areas.Admin/Areas/Admin/Pages/Role/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Senparc.Core.Models.DataBaseModel;
using Senparc.Scf.Core.Models;
using Senparc.Scf.Core.Models.DataBaseModel;
using Senparc.Scf.Service;
using Senparc.Service;

namespace Senparc.Areas.Admin.Areas.Admin.Pages
{
    public class RoleIndexModel : BaseAdminPageModel
    {
        private readonly SysRoleService _sysRoleService;

        public RoleIndexModel(SysRoleService sysRoleService)
        {
            CurrentMenu = "Role";
            this._sysRoleService = sysRoleService;
        }

        [BindProperty(SupportsGet = true)]
        public int PageIndex { get; set; } = 1;

        /// <summary>
        /// 
        /// </summary>
        public PagedList<SysRole> SysRoles { get; set; }

        public async Task OnGetAsync()
        {
            SysRoles = await _sysRoleService.GetObjectListAsync(PageIndex, 10, _ => true, _ => _.AddTime, Scf.Core.Enums.OrderingType.Descending);
        }

        public IActionResult OnPostDelete(string[] ids)
        {
            foreach (var id in ids)
            {
                _sysRoleService.DeleteObject(_ => _.Id == id);
            }

            return RedirectToPage("./Index");
        }
    }
}

src/Senparc.Areas.Admin/Areas/Admin/Pages/Role/Permission.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Senparc.Core.Models.DataBaseModel;
using Senparc.Scf.Core.Models.DataBaseModel;
using Senparc.Scf.Service;
using Senparc.Service;

namespace Senparc.Areas.Admin.Areas.Admin
{
    public class PagesRolePermissionModel : BaseAdminPageModel
    {
        private readonly SysRoleService _sysRoleService;
        private readonly SysPermissionService _sysPermissionService;

        //private readonly SysRoleMenuService _sysRoleMenuService;
        private readonly SysMenuService _sysMenuService;

        public PagesRolePermissionModel(SysMenuService sysMenuService, SysRoleService sysRoleService, SysPermissionService sysPermissionService)
        {
            CurrentMenu = "Role";
            _sysRoleService = sysRoleService;
            _sysPermissionService = sysPermissionService;
            //_sysRoleMenuService = sysRoleMenuService;
            _sysMenuService = sysMenuService;
        }

        /// <summary>
        /// 
        /// </summary>
        [BindProperty(SupportsGet = true)]
        public string RoleId { get; set; }

        /// <summary>
        /// 
        /// </summary>
        public SysRole SysRoleInfo { get; set; }

        public async Task OnGetAsync()
        {
            SysRoleInfo = await _sysRoleService.GetObjectAsync(_ => _.Id == RoleId);            
        }

        public async Task<IActionResult> OnGetRolePermissionAsync(string roleId)
        {
            var data = await _sysPermissionService.GetFullListAsync(_ => _.RoleId == roleId);
            return Ok(data);
        }

        public async Task<IActionResult> OnPostAsync(IEnumerable<SysPermissionDto> sysMenuDto)
        {
            if (!sysMenuDto.Any())
            {
                return Ok(false);
            }
            await _sysPermissionService.AddAsync(sysMenuDto);
            return Ok(true);
        }
    }
}

src/Senparc.Areas.Admin/Areas/Admin/Pages/Role/Edit.cshtml
@page
@model Senparc.Areas.Admin.Areas.Admin.Pages.RoleEditModel
@{
    ViewData["Title"] = $"{(!string.IsNullOrEmpty(Model.Id) ? "编辑" : "新增")}角色";
}
@section breadcrumbs{
    <li>系统管理</li>
    <li>
        <a asp-Page="/Role/Index" asp-area="Admin">角色管理</a>
    </li>
    <li>
        @ViewData["Title"]
    </li>
}
<!-- START row-->

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <form class="form-horizontal form-label-left" novalidate asp-action="Edit" asp-area="Admin" method="post">
                    <input type="hidden" asp-for="SysRoleDto.Id" />

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">
                            角色名称
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="SysRoleDto.RoleName" type="text" data-validate-length="1,150" required class="form-control" placeholder="请输入菜单名称">
                            <span asp-validation-for="SysRoleDto.RoleName" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">
                            角色代码
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="SysRoleDto.RoleCode" type="text" data-validate-length="0,350" class="form-control" required placeholder="请输入菜单地址">
                            <span asp-validation-for="SysRoleDto.RoleCode" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">
                            是否启用
                        </label>
                        <div class="col-md-4 col-sm-4 col-xs-12">
                            <div class="checkbox">
                                <label>
                                    <input type="checkbox" asp-for="SysRoleDto.Enabled" class="flat">
                                </label>
                            </div>
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">
                            说明
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="SysRoleDto.Remark" type="text" data-validate-length="1,150" class="form-control" placeholder="请输入说明">
                            <span asp-validation-for="SysRoleDto.Remark" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="item form-group">
                        <label class="control-label col-md-3 col-sm-3 col-xs-12" for="textarea">
                            备注
                        </label>
                        <div class="col-md-6 col-sm-6 col-xs-12">
                            <input asp-for="SysRoleDto.AdminRemark" type="text" data-validate-length="1,150" class="form-control" placeholder="请输入备注">
                            <span asp-validation-for="SysRoleDto.AdminRemark" class="text-danger"></span>
                        </div>
                    </div>

                    <div class="ln_solid"></div>

                    <div class="form-group">
                        <div class="col-md-6 col-md-offset-3">
                            <a asp-page="./Index" class="btn btn-primary">取消</a>
                            <input type="submit" class="btn btn-success" value="提交">
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

src/Senparc.Areas.Admin/Areas/Admin/Pages/Role/Index.cshtml
@page
@model Senparc.Areas.Admin.Areas.Admin.Pages.RoleIndexModel
@{
    ViewData["Title"] = "角色管理";
}
@section breadcrumbs{
    <li>系统管理</li>
    <li>
        角色管理
    </li>
}

<div class="row">

    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="pull-left" style="width: 100%">
                <div class="row">
                    <div class="col-xs-12 col-md-2 col-lg-2">
                        <a asp-page="Edit" asp-route-id="" title="新增" class="btn-sm btn btn-success">
                            <em class="fa fa-plus"></em> &nbsp;<small>新增</small>
                        </a>
                        <label for="deleteBtn" class="btn-sm btn btn-danger" title="删除">
                            <em class="fa fa-trash-o"></em> &nbsp;<small>删除</small>
                            <input type="submit" id="deleteBtn" onclick="deleteCheck('ids','deleteForm'); return false;" form="deleteForm" class="hidden" value="删除" />
                        </label>
                    </div>
                    @*<div class="col-xs-12 col-md-10 col-lg-10 form-horizontal form-label-left">
                            <form id="searchForm" asp-page="/CommodityCategory/Index" asp-area="Admin" method="get">
                                <div class="form-group">
                                    <label class="control-label col-md-1 col-sm-1 col-xs-6" for="first-name">
                                        分类名称
                                    </label>
                                    <div class="col-md-2 col-sm-2 col-xs-6">
                                        <input type="text" asp-for="SearchCategoryDto.Name" class="form-control col-md-7 col-xs-12">
                                    </div>

                                    <label class="control-label col-md-1 col-sm-1 col-xs-6" for="first-name">
                                        父级分类
                                    </label>
                                    <div class="col-md-2 col-sm-2 col-xs-6">
                                        <select class="form-control" asp-for="SearchCategoryDto.ParentId" asp-items="Model.CommodityCategorySelectListItems">
                                            <option>请选择</option>
                                        </select>
                                    </div>

                                    <div class="col-md-2 col-sm-2 col-xs-6">
                                        <input type="submit" class="btn btn-primary" value="查询" />
                                    </div>
                                </div>
                            </form>
                        </div>*@
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="x_content">
                @*<p>Add class <code>bulk_action</code> to table for bulk actions options on row select</p>*@
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr class="headings">
                                <th>
                                    <input type="checkbox" id="check-all" class="flat">
                                </th>
                                <th class="column-title">角色名称</th>
                                <th class="column-title">角色代码 </th>
                                <th class="column-title">备注</th>
                                <th class="column-title">说明</th>
                                <th class="column-title">添加时间 </th>
                                <th class="column-title">操作 </th>
                                <th class="bulk-actions" colspan="16">
                                    <a class="antoo" style="color:#fff; font-weight:500;">
                                        已选中 <span class="action-cnt"> </span>
                                        <i class="fa fa-chevron-down"></i>
                                    </a>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.SysRoles)
                            {
                                <tr class="pointer">
                                    <td class="a-center ">
                                        <input type="checkbox" class="flat table_records" name="ids" form="deleteForm" value="@item.Id">
                                    </td>
                                    <td class=" ">@item.RoleName </td>
                                    <td class=" ">@item.RoleCode</td>
                                    <td class=" ">@item.AdminRemark</td>
                                    <td class=" ">@item.Remark</td>
                                    <td class=" "> @item.AddTime.ToShortDateString()</td>
                                    <td class=" ">
                                        <a asp-page="Edit" asp-route-id="@item.Id" title="编辑" class="btn-xs btn btn-info">
                                            <em class="fa fa-pencil-square-o">编辑</em>
                                        </a>
                                        <a asp-page="Permission" asp-route-RoleId="@item.Id" title="权限" class="btn-xs btn btn-info">
                                            <em class="fa fa-pencil-square-o">权限</em>
                                        </a>
                                        @*<button data-content="@item.Id" title="复制商品链接" class="copyLink btn-xs btn btn-default">
                                                复制<em class="fa fa-clone"></em>
                                            </button>*@
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="text-center p jpagerbar">
                    @Html.Raw((Html.PagerBar(Model.SysRoles, new PagerBarSettings(Url.Page("/Role/Index", new
       {
           pageIndex = "{0}"
       }))
       {
           NoRecordTip = "暂无数据",
           ShowTotalCount = true
       })))
                </div>
            </div>
        </div>
    </div>
</div>
<form method="post" asp-page-handler="Delete" id="deleteForm"></form>

src/Senparc.Areas.Admin/Areas/Admin/Pages/Role/Permission.cshtml
@page
@model Senparc.Areas.Admin.Areas.Admin.PagesRolePermissionModel
@{
    ViewData["Title"] = $"{Model.SysRoleInfo.RoleName}角色权限列表";
}

@section Style{
    <link href="~/node_modules/@@ztree/ztree_v3/css/zTreeStyle/zTreeStyle.css" rel="stylesheet" />
}


@section breadcrumbs{
    <li>系统管理</li>
    <li>
        <a asp-Page="/Role/Index" asp-area="Admin">角色管理</a>
    </li>
    <li>
        角色权限管理
    </li>
}
<!-- START row-->

<div class="row">
    <div class="col-md-12 col-sm-12 col-xs-12">
        <div class="x_panel">
            <div class="x_content">
                <h3>
                    @Model.SysRoleInfo.RoleName - 权限设置
                </h3>
                <div class="treeContainer">
                    <ul id="tree" class="ztree"></ul>
                </div>
                <a asp-page="Index" class="btn btn-default">返回</a>
                <a class="btn btn-primary" id="save">保存</a>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script src="~/node_modules/@@ztree/ztree_v3/js/jquery.ztree.core.min.js"></script>
    <script src="~/node_modules/@@ztree/ztree_v3/js/jquery.ztree.excheck.min.js"></script>
    <script src="~/js/Admin/Pages/Role/Permission.js"></script>
}