src/Senparc.Areas.Admin/Areas/Admin/Pages/XscfModule/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Senparc.CO2NET.Extensions;
using Senparc.Core.Models.DataBaseModel;
using Senparc.Scf.Core.Enums;
using Senparc.Scf.Core.Models;
using Senparc.Scf.Core.Models.DataBaseModel;
using Senparc.Scf.Service;
using Senparc.Scf.XscfBase;
using Senparc.Service;
using Microsoft.Extensions.DependencyInjection;
using Senparc.CO2NET.Trace;

namespace Senparc.Areas.Admin.Areas.Admin.Pages
{
    public class XscfModuleIndexModel : BaseAdminPageModel
    {
        private readonly IServiceProvider _serviceProvider;
        private readonly XscfModuleServiceExtension _xscfModuleService;
        private readonly SysMenuService _sysMenuService;

        public XscfModuleIndexModel(IServiceProvider serviceProvider, XscfModuleServiceExtension xscfModuleService, SysMenuService sysMenuService)
        {
            CurrentMenu = "XscfModule";

            this._serviceProvider = serviceProvider;
            this._xscfModuleService = xscfModuleService;
            this._sysMenuService = sysMenuService;
        }

        [BindProperty(SupportsGet = true)]
        public int PageIndex { get; set; } = 1;

        /// <summary>
        /// 数据库已存的XscfModules
        /// </summary>
        public PagedList<XscfModule> XscfModules { get; set; }
        public List<IXscfRegister> NewXscfRegisters { get; set; }

        private void LoadNewXscfRegisters(PagedList<XscfModule> xscfModules)
        {
            NewXscfRegisters = Senparc.Scf.XscfBase.Register.RegisterList.Where(z => !z.IgnoreInstall && !xscfModules.Exists(m => m.Uid == z.Uid && m.Version == z.Version)).ToList() ?? new List<IXscfRegister>();
        }

        public async Task OnGetAsync()
        {
            //更新菜单缓存
            await _sysMenuService.GetMenuDtoByCacheAsync(true).ConfigureAwait(false);
            XscfModules = await _xscfModuleService.GetObjectListAsync(PageIndex, 10, _ => true, _ => _.AddTime, Scf.Core.Enums.OrderingType.Descending);
            LoadNewXscfRegisters(XscfModules);
        }

        /// <summary>
        /// 扫描新模块
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> OnGetScanAsync(string uid)
        {
            var result = await _xscfModuleService.InstallModuleAsync(uid);
            XscfModules = result.Item1;
            base.SetMessager(Scf.Core.Enums.MessageType.info, result.Item2, true);

            //if (backpage=="Start")
            return RedirectToPage("Start", new { uid = uid });//始终到详情页
            //return RedirectToPage("Index");
        }
    }
}

src/Senparc.Areas.Admin/Areas/Admin/Pages/XscfModule/Start.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Senparc.CO2NET.Cache;
using Senparc.CO2NET.Extensions;
using Senparc.CO2NET.Helpers;
using Senparc.Scf.Core.Enums;
using Senparc.Scf.Service;
using Senparc.Scf.XscfBase;
using Senparc.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Senparc.Areas.Admin.Areas.Admin.Pages
{
    public class XscfModuleStartModel : BaseAdminPageModel
    {
        public IXscfRegister XscfRegister { get; set; }
        private readonly SysMenuService _sysMenuService;
        public Senparc.Scf.Core.Models.DataBaseModel.XscfModule XscfModule { get; set; }
        public Dictionary<IXscfFunction, List<FunctionParammeterInfo>> FunctionParammeterInfoCollection { get; set; } = new Dictionary<IXscfFunction, List<FunctionParammeterInfo>>();

        XscfModuleService _xscfModuleService;
        IServiceProvider _serviceProvider;

        public List<string> XscfModuleUpdateLog { get; set; }

        public string Msg { get; set; }
        public object Obj { get; set; }

        public XscfModuleStartModel(IServiceProvider serviceProvider, XscfModuleService xscfModuleService, SysMenuService sysMenuService)
        {
            _serviceProvider = serviceProvider;
            _xscfModuleService = xscfModuleService;
            _sysMenuService = sysMenuService;
        }

        public async Task OnGetAsync(string uid)
        {
            if (uid.IsNullOrEmpty())
            {
                throw new Exception("模块编号未提供！");
            }


            XscfModule = await _xscfModuleService.GetObjectAsync(z => z.Uid == uid).ConfigureAwait(false);

            if (XscfModule == null)
            {
                throw new Exception("模块未添加！");
            }

            if (!XscfModule.UpdateLog.IsNullOrEmpty())
            {
                XscfModuleUpdateLog = XscfModule.UpdateLog
                    .Split(new[] { "\r", "\n" }, StringSplitOptions.RemoveEmptyEntries)
                    .ToList();
            }
            else
            {
                XscfModuleUpdateLog = new List<string>();
            }

            XscfRegister = Senparc.Scf.XscfBase.Register.RegisterList.FirstOrDefault(z => z.Uid == uid);
            if (XscfRegister == null)
            {
                throw new Exception($"模块丢失或未加载（{Senparc.Scf.XscfBase.Register.RegisterList.Count}）！");
            }

            foreach (var functionType in XscfRegister.Functions)
            {
                var function = _serviceProvider.GetService(functionType) as FunctionBase;//如：Senparc.Xscf.ChangeNamespace.Functions.ChangeNamespace
                FunctionParammeterInfoCollection[function] = function.GetFunctionParammeterInfo().ToList();
            }
        }

        /// <summary>
        /// 更新状态
        /// </summary>
        /// <param name="id"></param>
        /// <param name="toState"></param>
        /// <returns></returns>
        public async Task<IActionResult> OnGetChangeStateAsync(int id, XscfModules_State toState)
        {
            var module = await _xscfModuleService.GetObjectAsync(z => z.Id == id).ConfigureAwait(false);

            if (module == null)
            {
                throw new Exception("模块未添加！");
            }

            module.UpdateState(toState);
            await _xscfModuleService.SaveObjectAsync(module).ConfigureAwait(false);
            base.SetMessager(MessageType.success, "状态变更成功！");
            return RedirectToPage("Start", new { uid = module.Uid });
        }

        public async Task<IActionResult> OnPostRunFunctionAsync(string xscfUid, string xscfFunctionName, string xscfFunctionParams)
        {
            var xscfRegister = Senparc.Scf.XscfBase.Register.RegisterList.FirstOrDefault(z => z.Uid == xscfUid);

            if (xscfRegister == null)
            {
                return new JsonResult(new { success = false, msg = "模块未注册！" });
            }

            var xscfModule = await _xscfModuleService.GetObjectAsync(z => z.Uid == xscfRegister.Uid).ConfigureAwait(false);
            if (xscfModule == null)
            {
                return new JsonResult(new { success = false, msg = "当前模块未安装！" });
            }

            if (xscfModule.State != XscfModules_State.开放)
            {
                return new JsonResult(new { success = false, msg = $"当前模块状态为【{xscfModule.State}】,必须为【开放】状态的模块才可执行！\r\n此外，如果您强制执行此方法，也将按照未通过验证的程序集执行，因为您之前安装的版本可能已经被新的程序所覆盖。" });
            }

            FunctionBase function = null;

            foreach (var functionType in xscfRegister.Functions)
            {
                var fun = _serviceProvider.GetService(functionType) as FunctionBase;//如：Senparc.Xscf.ChangeNamespace.Functions.ChangeNamespace
                var functionParameters = fun.GetFunctionParammeterInfo().ToList();
                if (fun.Name == xscfFunctionName)
                {
                    function = fun;
                    break;
                }
            }

            if (function == null)
            {
                return new JsonResult(new { success = false, msg = "方法未匹配上！" });
            }

            var paras = SerializerHelper.GetObject(xscfFunctionParams, function.FunctionParameterType) as IFunctionParameter;
            //var paras = function.GenerateParameterInstance();

            var result = function.Run(paras);

            var tempId = "Xscf-FunctionRun-" + Guid.NewGuid().ToString("n");
            //记录日志缓存
            if (!result.Log.IsNullOrEmpty())
            {
                var cache = _serviceProvider.GetObjectCacheStrategyInstance();
                await cache.SetAsync(tempId, result.Log, TimeSpan.FromMinutes(5));//TODO：可设置
            }

            var data = new { success = result.Success, msg = result.Message.HtmlEncode(), log = result.Log, exception = result.Exception?.Message, tempId = tempId };
            return new JsonResult(data);
        }

        /// <summary>
        /// 获取日志
        /// </summary>
        /// <param name="tempId"></param>
        /// <returns></returns>
        public async Task<IActionResult> OnGetLogAsync(string tempId)
        {
            var cache = _serviceProvider.GetObjectCacheStrategyInstance();
            var log = await cache.GetAsync<string>(tempId);
            if (log == null)
            {
                return Content("日志文件不存在或已下载！");
            }

            await cache.RemoveFromCacheAsync(tempId);

            return File(Encoding.UTF8.GetBytes(log), "text/plain", $"xscf-log-{tempId}.txt");
        }

        /// <summary>
        /// 删除模块
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public async Task<IActionResult> OnPostDeleteAsync(int id)
        {
            var module = await _xscfModuleService.GetObjectAsync(z => z.Id == id).ConfigureAwait(false);

            if (module == null)
            {
                throw new Exception("模块未添加！");
            }

            //删除菜单
            Func<Task> uninstall = async () =>
            {
                //删除菜单
                var menu = await _sysMenuService.GetObjectAsync(z => z.Id == module.MenuId).ConfigureAwait(false);
                if (menu != null)
                {
                    //删除菜单
                    await _sysMenuService.DeleteObjectAsync(menu).ConfigureAwait(false);
                    //更新菜单缓存
                    await _sysMenuService.GetMenuDtoByCacheAsync(true).ConfigureAwait(false);
                }
                await _xscfModuleService.DeleteObjectAsync(module).ConfigureAwait(false);
            };


            //尝试从已加载的模块中执行删除过程
            var register = Senparc.Scf.XscfBase.Register.RegisterList.FirstOrDefault(z => z.Uid == module.Uid);
            if (register == null)
            {
                //直接删除，如dll已经不存在，可能引发此问题，只能在当前系统内直接执行删除
                await uninstall().ConfigureAwait(false);
            }
            else
            {
                await register.UninstallAsync(_serviceProvider, uninstall).ConfigureAwait(false);
            }

            return RedirectToPage("Index");
        }

    }
}

src/Senparc.Areas.Admin/Areas/Admin/Pages/XscfModule/Index.cshtml
@page
@model Senparc.Areas.Admin.Areas.Admin.Pages.XscfModuleIndexModel
@using Senparc.Scf.Core.Areas;
@using Senparc.Scf.XscfBase;
@{
    ViewData["Title"] = "模块管理";
}
@section breadcrumbs{
    <li>扩展模块</li>
    <li>模块管理</li>
}

<div class="row">

    <div class="col-md-12 col-sm-12 col-xs-12">
        @if (Model.NewXscfRegisters.Count > 0)
        {

            <div class="x_panel">
                <div class="pull-left" style="width: 100%">
                    <div class="row">
                        <div class="col-xs-12 col-md-8 col-lg-8">
                            <h3>发现新模块！</h3>
                        </div>
                    </div>
                </div>
                <div class="clearfix"></div>
                <div class="x_content">
                    @*<p>Add class <code>bulk_action</code> to table for bulk actions options on row select</p>*@
                    <div class="table-responsive">
                        <table class="table  bulk_action">
                            <thead>
                                <tr class="headings">
                                    <th class="column-title">模块名称</th>
                                    <th class="column-title">菜单名称（显示名称）</th>
                                    <th class="column-title">版本号</th>
                                    <th class="column-title">唯一编码（全局唯一）</th>
                                    <th class="column-title">操作 </th>
                                    <th class="bulk-actions" colspan="16">
                                        <a class="antoo" style="color:#fff; font-weight:500;">
                                            已选中 <span class="action-cnt"> </span>
                                            <i class="fa fa-chevron-down"></i>
                                        </a>
                                    </th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model.NewXscfRegisters)
                                {
                                <tr class="pointer">
                                    <td class=" "><i class="fa fa-cubes"></i> @item.Name </td>
                                    <td class=" "><i class="@item.Icon"></i> @item.MenuName</td>
                                    <td class=" "> <i class="fa fa-code-fork"></i> v@(item.Version)</td>
                                    <td class=" "><i class="fa fa-shield"></i> @item.Uid</td>
                                    <td class=" ">
                                        <a asp-page="Index" asp-page-handler="Scan" asp-route-uid="@item.Uid" title="扫描" class="btn-sm btn btn-success">
                                            <em class="glyphicon glyphicon-gift"></em> &nbsp;<small>安装</small>
                                        </a>
                                        @*<a asp-page="Start" asp-route-uid="@item.Uid" title="设置" class="btn-xs btn btn-info">
                <em class="fa fa-gear">设置</em>
            </a>*@
                                    </td>
                                </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>

        }

        <div class="x_panel">
            <div class="pull-left" style="width: 100%">
                <div class="row">
                    <div class="col-xs-12 col-md-8 col-lg-8">
                        <h3>已安装模块</h3>
                    </div>
                </div>
            </div>
            <div class="clearfix"></div>
            <div class="x_content">
                @*<p>Add class <code>bulk_action</code> to table for bulk actions options on row select</p>*@
                <div class="table-responsive">
                    <table class="table table-striped jambo_table bulk_action">
                        <thead>
                            <tr class="headings">
                                <th>
                                    <input type="checkbox" id="check-all" class="flat">
                                </th>
                                <th class="column-title">菜单名称 / 版本号</th>
                                <th class="column-title">模块名称 / 唯一编码（全局唯一）</th>
                                <th class="column-title">状态</th>
                                @*<th class="column-title">备注</th>
                                <th class="column-title">说明</th>*@
                                <th class="column-title">添加时间 </th>
                                <th class="column-title">操作 </th>
                                <th class="bulk-actions" colspan="16">
                                    <a class="antoo" style="color:#fff; font-weight:500;">
                                        已选中 <span class="action-cnt"> </span>
                                        <i class="fa fa-chevron-down"></i>
                                    </a>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model.XscfModules)
                            {
                                var xscfRegister = Model.XscfRegisterList.FirstOrDefault(z => z.Uid == item.Uid);
                                <tr class="pointer">
                                    <td class="a-center ">
                                        <input type="checkbox" class="flat table_records" name="ids" form="deleteForm" value="@item.Id">
                                    </td>
                                    <td class=" ">
                                        <i class="@xscfRegister?.Icon"></i> @item.MenuName<br />
                                        <i class="fa fa-code-fork"></i> v@(item.Version)
                                    </td>
                                    <td class=" ">
                                        <i class="fa fa-cubes"></i> @item.Name<br />
                                        <i class="fa fa-shield"></i> @item.Uid
                                    </td>
                                    <td class=" ">@item.State.ToString()</td>
                                    @*<td class=" ">@item.AdminRemark</td>
                                    <td class=" ">@item.Remark</td>*@
                                    <td class=" "> @item.AddTime.ToString()</td>
                                    <td class=" ">
                                        <a asp-page="Start" asp-route-uid="@item.Uid" title="操作" class="btn-xs btn btn-info">
                                            <em class="fa fa-gear"> 操作</em>
                                        </a>
                                        @if (xscfRegister?.GetAreaHomeUrl() is string homeUrl &&
                                          !homeUrl.IsNullOrEmpty())
                                        {
                                            <a href="@homeUrl" title="主页" class="btn-xs btn btn-danger">
                                                <em class="fa fa-home">
                                                    主页
                                                </em>
                                            </a>
                                        }
                                    </td>
                                </tr>
                            }
                        </tbody>
                    </table>
                </div>
                <div class="text-center p jpagerbar">
                    @Html.Raw((Html.PagerBar(Model.XscfModules, new PagerBarSettings(Url.Page("/XscfModule/Index", new
               {
                   pageIndex = "{0}"
               }))
               {
                   NoRecordTip = "暂无数据",
                   ShowTotalCount = true
               })))
                </div>
            </div>
        </div>
    </div>
</div>